<script lang="ts">
  import TwitchChannelGrid from '$lib/TwitchChannelGrid/TwitchChannelGrid.svelte';

  let channels = new Map<string, string>([
    [ 'nukadokotaro', 'ぬかどこたろう' ],
    [ 'luluiluu', 'るるいチャン' ],
    [ 'dezabudzb', 'デザ部のもりもり' ],
    [ 'puu3', 'puu3' ],
    [ 'amiya2008', '網屋' ],
    [ 'nevadatomato', 'ネバダのとまと' ],
    [ 'darumaramen', 'だるまラーメン' ],
    [ 'chandy______', 'ちゃんディー' ],
    [ 'mimyou', 'ミミョウ' ],
    [ 'kikinene', 'ききねー' ],
    [ 'kappy_games', 'かっぴーげーむす' ],
    [ 'shupeso3', 'しゅぺそ' ],
    [ 'jooohn15', 'じょょょん' ],
    [ 'gngn_kosino', 'ぐんこしの' ],
    [ 'hippepen', 'ひっぺと申します' ],
    [ 'maedatadakatu', 'けつドレ' ],
    [ 'takajisan', 'たかぢ' ],
    [ 'eviiiino', 'えびぃの' ],
    [ 'william_naokichi', 'ウィリアムなおきち' ],
    [ 'dezabudzb', 'デザ部のやまやま' ],
    [ 'rasi__yattane', 'らっしーやったね' ],
    [ 'kassy_games', 'KASSY' ],
    [ 'ww_okasama_ww', '岡様' ],
    [ 'yappy3838', 'やっぴーちゃんねる' ],
    [ 'komachi_key', '調子こきまろのこまち' ],
    [ 'chiyonog', 'ちよん' ],
    [ 'okasinokoyanokoya', 'お菓子の小屋' ],
    [ 'simiryuuu', 'しみりゅー' ],
    [ 'haainico', '太陽神灰にこ' ],
    [ 'piggyhoggyboo', 'PiggyHoggyBoo' ],
    [ 'samuraimori3', 'もりさん' ],
    [ 'ty9nine', 'ないん' ],
    [ 'zamurai_japan', 'ざむらいジャパン' ],
    [ 'kemum4k1', '煙巻' ],
    [ 'orangista12', 'たくぷー' ],
    [ 'nitroro_', 'にとろろ' ],
    [ 'dobashi_gengoro', 'どばし校長' ],
    [ 'wan2tan', 'ワンたん' ],
    [ 'watawata1218', 'わた軍団' ],
    [ 'moribuden_seseri', 'もりぶでん' ],
    [ 'kisetsu_no_mjs', '季節の饅頭を添えたい' ],
    [ 'kentoobeta', 'ケントゥベータ' ],
    [ 'ganbaru_tarou', 'ガンバルタロウ' ],
    [ 'momonoeyumo', '桃枝ゆも' ],
    [ 'bal863', '普通のばる' ],
    [ 'momotsuyo', 'パンツマン' ],
    [ 'aotadado', 'あおちゃん' ],
    [ 'norishio_42', 'Norishio42' ],
    [ 'aoiuru_owl', '葵うる' ],
    [ 'tenshimoko', '天使㋲子' ],
    [ 'jerontro_g', 'ぢぇろ' ],
    [ 'uninorem', 'うにのれむ' ],
    [ 'gahu3', 'くま沢ガフ美' ],
    [ 'maori215', 'おきつね杏ちゃん' ],
    [ 'tmwooody', 'Tm-woody' ],
    [ 'brosutar5v', '女装のブロスター' ],
    [ 'pestalozzi999', 'pestalozzi999' ],
    [ 'tashiro_masashi_', '田代まさし' ],
    [ 'tasiota', 'たしおた' ],
    [ 'senzsan', 'せんず' ],
    [ 'ryoubeni', 'ryoubeni' ],

  ]);
</script>

<TwitchChannelGrid {channels} />
